FROM node:20
WORKDIR /db
COPY drizzle/ drizzle/
COPY drizzle.config.ts .
COPY schema/ schema/
COPY package*.json .
RUN npm install
EXPOSE 5432
CMD ["/bin/sh", "-c", "sleep 3 && npm run drizzle:migrate"]
